ipc = true

preload = $HOME/.config/hypr/wallpapers/flowerlady.png
preload = $HOME/.config/hypr/wallpapers/nighthaven.png
preload = $HOME/.config/hypr/wallpapers/windmill.jpg

wallpaper {
    monitor = eDP-1
    path = $HOME/.config/hypr/wallpapers/windmill.jpg
    fit_mode = cover
}
