# preload = ~/pictures/wallpaper.jpeg
preload = $HOME/.config/hypr/wallpapers/1.jpeg
preload = $HOME/.config/hypr/wallpapers/2.jpeg
preload = $HOME/.config/hypr/wallpapers/3.jpeg
preload = $HOME/.config/hypr/wallpapers/4.jpeg
preload = $HOME/.config/hypr/wallpapers/5.jpeg
preload = $HOME/.config/hypr/wallpapers/6.jpeg
preload = $HOME/.config/hypr/wallpapers/7.jpeg
preload = $HOME/.config/hypr/wallpapers/8.jpeg
preload = $HOME/.config/hypr/wallpapers/9.jpeg
preload = $HOME/.config/hypr/wallpapers/10.jpeg
preload = $HOME/.config/hypr/wallpapers/11.jpeg
preload = $HOME/.config/hypr/wallpapers/12.jpeg
preload = $HOME/.config/hypr/wallpapers/13.jpeg
preload = $HOME/.config/hypr/wallpapers/14.jpeg
preload = $HOME/.config/hypr/wallpapers/15.jpeg
preload = $HOME/.config/hypr/wallpapers/16.jpeg
preload = $HOME/.config/hypr/wallpapers/17.jpeg

wallpaper = ,$HOME/.config/hypr/wallpapers/1.jpeg
wallpaper = ,$HOME/.config/hypr/wallpapers/2.jpeg
wallpaper = ,$HOME/.config/hypr/wallpapers/3.jpeg
wallpaper = ,$HOME/.config/hypr/wallpapers/4.jpeg
wallpaper = ,$HOME/.config/hypr/wallpapers/5.jpeg
wallpaper = ,$HOME/.config/hypr/wallpapers/6.jpeg
wallpaper = ,$HOME/.config/hypr/wallpapers/7.jpeg
wallpaper = ,$HOME/.config/hypr/wallpapers/8.jpeg
wallpaper = ,$HOME/.config/hypr/wallpapers/9.jpeg
wallpaper = ,$HOME/.config/hypr/wallpapers/10.jpeg
wallpaper = ,$HOME/.config/hypr/wallpapers/11.jpeg
wallpaper = ,$HOME/.config/hypr/wallpapers/12.jpeg
wallpaper = ,$HOME/.config/hypr/wallpapers/13.jpeg
wallpaper = ,$HOME/.config/hypr/wallpapers/14.jpeg
wallpaper = ,$HOME/.config/hypr/wallpapers/15.jpeg
wallpaper = ,$HOME/.config/hypr/wallpapers/16.jpeg
wallpaper = ,$HOME/.config/hypr/wallpapers/17.jpeg
