$font = Monospace

general {
    hide_cursor = false
}

auth {
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
        retry_delay = 250 # in milliseconds
    }
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 0, 2, linear
    animation = fadeOut, 1, 2, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    path = $HOME/.config/hypr/wallpapers/lockscreen.jpeg
    blur_passes = 1
    blur_size = 1
}

input-field {
    size = 5%, 4%

    font_color = rgba(200, 200, 200, 1)
    font_family = Monospace
    placeholder_text = password
    check_text = Logging in...

    inner_color = rgba(0, 0, 0, 0.0) # no fill
    check_color = rgba(0, 0, 0, 0.0) # no fill
    fail_color = rgba(0, 0, 0, 0.0) # no fill
    
    dots_size = 0

    placeholder_text = 
    fade_on_empty = false

    outline_thickness = 0
    halign = right
    valign = bottom
}

# TIME
label {
    text = <span font_weight="bold"> $TIME </span>
    font_size = 120
    font = Sans

    position = 0, -10%
    halign = center
    valign = top
}

# DATE
label {
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font = bold
    font_size = 25

    position = 0, -150
    halign = center
    valign = top
}
