ipc = true

wallpaper {
    monitor = DP-2
    path = $HOME/.config/hypr/wallpapers/windmill.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = $HOME/.config/hypr/wallpapers/windmill.jpg
    fit_mode = cover
}
